# Generated by Django 5.0.3 on 2024-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='is_process',
            field=models.BooleanField(default=False),
        ),
    ]
