# Generated by Django 5.0.3 on 2024-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datafile_is_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='is_process',
            field=models.BooleanField(default=True),
        ),
    ]
